{
 "title": "Asic monitor",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Miners info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "asic_miner_info{}" }
   ]
  },
  {
   "title": "Total hashrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(asic_miner_status_ths_rt{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(asic_miner_status_power{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miner status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "asic_miner_status{}", "legendFormat": "__auto" },
    { "expr": "asic_miner_status_power{}", "legendFormat": "__auto" },
    { "expr": "asic_miner_status_uptime", "legendFormat": "__auto" },
    {
     "expr": "asic_miner_status_elapsed_time{}",
     "legendFormat": "__auto"
    },
    { "expr": "asic_miner_status_upfreq{}", "legendFormat": "__auto" },
    { "expr": "asic_miner_status_ths_rt{}", "legendFormat": "__auto" },
    {
     "expr": "asic_miner_status_power_limit{}",
     "legendFormat": "__auto"
    },
    { "expr": "asic_miner_status_efficiency{}", "legendFormat": "__auto" },
    {
     "expr": "asic_miner_status_input_voltage{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "asic_miner_temperature_env_temperature{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_avg_temperature{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_psu_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_left_board_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_left_board_chip_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_center_board_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_center_board_chip_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_right_board_temperature",
     "legendFormat": "__auto"
    },
    {
     "expr": "asic_miner_temperature_right_board_chip_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hashboard average temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "asic_miner_temperature_avg_temperature",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Inlet air (environment temperature)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "asic_miner_temperature_env_temperature{}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "asic_miner_fans_fan_speed_in", "legendFormat": "__auto" },
    { "expr": "asic_miner_fans_fan_speed_out", "legendFormat": "__auto" },
    { "expr": "asic_miner_fans_psu_fan_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "asic_miner_fans_fan_speed_in", "legendFormat": "{{ip}} - speed in" },
    { "expr": "asic_miner_fans_fan_speed_out", "legendFormat": "{{ip}} - speed out" }
   ]
  },
  {
   "title": "Pool",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    { "expr": "asic_pool_status", "legendFormat": "__auto" },
    {
     "expr": "asic_pool_status_last_share_time*1000",
     "legendFormat": "__auto"
    },
    { "expr": "asic_pool_status_reject_rate", "legendFormat": "__auto" }
   ]
  }
 ]
}